name: documentation

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install ghp-import sphinx==7.3.7 sphinx_rtd_theme==2.0.0 -e .
          sudo apt-get install make  # Ajouter cette ligne pour installer make

      - name: Build HTML
        run: | 
          cd docs/source
          make html

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/build/html
